### ISSUE TITLE
Title and URL in the wrong places in HTML

### ISSUE THREAD

**Issue by Mozinet-fr** [evilnickname/link-text-location-copier#1]
In Firefox 55.0.3 when I click on "Copy page title and location as HTML" menu item I copy: `<a href="It’s your data, we’re just living in it | Future Releases">https://blog.mozilla.org/futurereleases/2017/09/06/data-just-living/</a>` as an example.

**Comment by evilnickname** [comment]
That's strange. What platform are you on?

On my Windows machine in Firefox 55.0.3 (64 bit) I get `<a href="https://github.com/evilnickname/link-text-location-copier">undefined</a>` (as the [contextMenus.onClickData.linkText property is not implemented before Firefox 56](https://bugzilla.mozilla.org/show_bug.cgi?id=1343236)).

**Comment by evilnickname** [comment]
Ah, yes. Thanks for reporting it. I'll fix it asap.

**Comment by evilnickname** [comment]
I changed the order, and just submitted version 1.0.2 for review to AMO.

**Comment by evilnickname** [comment]
[Version 1.0.2](https://addons.mozilla.org/en-US/firefox/addon/link-text-and-location-copier/versions/1.0.2) is approved.
