### ISSUE TITLE
Copy URL without encode 

### ISSUE THREAD

**Issue by heX16** [evilnickname/link-text-location-copier#12]
Then copy non ANSI char is "encoded" (URL-encoded).

Example:
Original: https://ru.wikipedia.org/wiki/Заглавная_страница
Copy result: https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0

Yes, i known than its default behavior in Firefox, but please add options for disable this mode.

See also: http://kb.mozillazine.org/Network.standard-url.encode-query-utf8

PS: sorry for my English

**Comment by evilnickname** [comment]
This option has been added to version 1.4.5.

**Comment by heX16** [comment]
This option works fine (after rebooting the browser).
Many thanks! 🎉🎉🎉
