### ISSUE TITLE
Does not copy all selected text

### ISSUE THREAD

**Issue by DavidParkin** [evilnickname/link-text-location-copier#13]
Length of copied text appears to be limited to less than the selected text.

**Comment by evilnickname** [comment]
Hi David,

Do you have more information on this? What version of Firefox are you using? How long is the selection that gets truncated?

(There was [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1338898) that limited text selection to 150 characters, but that was fixed in Firefox 56.)

**Comment by DavidParkin** [comment]
Okay, I was using FF 54. Still working out what I will lose. Thanks for responding so quickly.
