### ISSUE TITLE
does not work inside frame

### ISSUE THREAD

**Issue by def00111** [evilnickname/link-text-location-copier#15]
use my workaround:

https://github.com/def00111/copy-link-text/blob/master/inject.js

**Comment by evilnickname** [comment]
Thanks, I will have a look at it.

**Comment by def00111** [comment]
You can test it here:
https://docs.oracle.com/javase/8/docs/api/

**Comment by evilnickname** [comment]
Solved in version 1.6.0.

Again, thanks for pointing this out and providing a workaround.
