### ISSUE TITLE
On addons.mozilla.org, menu is available but functions don't work

### ISSUE THREAD

**Issue by BoffinBrain** [evilnickname/link-text-location-copier#16]
On https://addons.mozilla.org/ all of the menu items are available but none of them will actually copy anything to the clipboard.

I believe this is due to the fact that AMO is a 'restricted' page and thus Firefox isn't allowing full functionality here. It does make me wonder, though, why does it allow the addon to even make menu items at all if that's the case?

**Comment by evilnickname** [comment]
As "[content scripts are currently blocked on addons.mozilla.org](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#WebExtension_APIs)," I don't doubt that's the case.

I tested by requesting host permission for addons.mozilla.org, but that had no effect. I'm afraid I can't fix this at this time. 

[There's a bug that could fix this](https://bugzilla.mozilla.org/show_bug.cgi?id=1334918), so I'll keep an eye on that.

**Comment by BoffinBrain** [comment]
If it can't work on AMO then that's fine. What confuses me is that the extension is allowed to modify the context menu, even though the actions performed by them are blocked. I guess context menu access is considered as a lower privilege level than accessing the clipboard?
