### ISSUE TITLE
Can't suppress content menu prefix for rich text

### ISSUE THREAD

**Issue by dgrobani** [evilnickname/link-text-location-copier#17]
I can't thank you enough for this addon. The rich text feature of CoLT was one of my most-used of all Firefox addons, and I'm delighted you've revived it.

In the 1.6.0 settings, the rich text entry doesn't enable editing, so the "Don't show context menu prefix" option isn't available.

Thanks!

**Comment by evilnickname** [comment]
I must have had a good reason to disallow editing of the rich text menu item, but I cannot recall what that must have been. So I added a checkbox to the modal, and now you edit them.

It might have had to with having to reset to the default settings before changes to show up, which I wanted to be able to do something about first. To circumvent that problem, I've added an import/export settings feature as well.

Version 1.7.0 is now available on AMO.
