### ISSUE TITLE
Inconsistent capitalization of default menu items

### ISSUE THREAD

**Issue by dgrobani** [evilnickname/link-text-location-copier#18]
The first two default menu items, "plain text" and "link text," are all lower-case, while "Rich Text" is capitalized. FWIW, I suggest "rich text."

Thanks!

**Comment by evilnickname** [comment]
I was under the assumption that 'Rich Text'  was some sort of trademark, but it doesn't seem to be. So, in version 1.7.0 (now available on AMO), Rich Text is lowercased.
