### ISSUE TITLE
Import settings default filter does not find exported settings

### ISSUE THREAD

**Issue by Secret-Code** [evilnickname/link-text-location-copier#19]
Export settings saves the file with .json extension.

But import settings has a default file filter of *.txt so you can't see the export file until you change to 'all files'.

The import settings file dialogue should have a filter like *.json.

**Comment by evilnickname** [comment]
Good catch, thank you. 

I completely forgot about that. I have just submitted version 1.8.1 which sets the `accept` attribute of the file input to JSON.
