### ISSUE TITLE
options styling prevents closing dialog

### ISSUE THREAD

**Issue by atomGit** [evilnickname/link-text-location-copier#20]
see: https://upload.disroot.org/r/3OjAfIlH#NhsuZdme649BK7jnbe23TtMwn56qO4Hvh4XvtCHpFy4=

when opening the advanced section, the save/cancel buttons are off the bottom of the display and thus cannot be clicked - ESC does not dismiss the dialog either

this is with a 1080p display and `layout.css.devPixelsPerPx` set to 1.3 to zoom the FF UI and everything in it, including the page, else nothing is readable on a 17" display

i suspect the problem is simply some CSS styling

**Comment by evilnickname** [comment]
Thanks for the report. I know the options page is in need of a complete overhaul, and I hope to find some time for that very soon.

Until then closing the advanced section (by clicking/toggling the 'custom format variables' again) should bring the buttons back into view.

**Comment by evilnickname** [comment]
@atomGit I've just submitted an update, which now opens the options page in a new tab, and moves the edit dialog a bit higher up the page. This should potentially fix your issue.

**Comment by atomGit** [comment]
thank you sir :)

great extension by the way - i was missing CoLT's ability to paste html as hyperlinks to editors like TinyMCE (WordPress)

**Comment by atomGit** [comment]
your fix worked fine in my case, but it might not on smaller screens - this solution should work in all cases:

```
#formatDialog {
    overflow: scroll;
}
```
i'll let you close this - thanks!

**Comment by evilnickname** [comment]
In version 1.8.5, I moved the buttons above the 'Custom format variables' element, added a `max-height` and `overflow-y` to the dialog, and now, I think, all this should be fixed.

**Comment by evilnickname** [comment]
Closing the issue, as I believe latest version should solve most cases.
