### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by yulelong** [evilnickname/link-text-location-copier#3]
is keyboard shortcuts in popup menu possible? just like "copy link text (x)" provided by the colt addon

**Comment by evilnickname** [comment]
I've looked into it, and at the moment Firefox WebExtentions cannot set custom keyboard shortcuts for context(sub)menu entries. You can only set a (non-configurable) shortcut for an action, which would probably interfere with other shortcuts.

If and when shortcuts become possible, I'll definitely try to add them.
