### ISSUE TITLE
Custom Formats?

### ISSUE THREAD

**Issue by pmorch** [evilnickname/link-text-location-copier#6]
Thank you, thank you, thank you for starting a WebExtensions version of CoLT, my favorite Firefox add-on.

I could see in `link-text-location-copier/linktextlocationcopier.js`, that the links and their formats are hard-coded.

Any chance of that being configurable as in CoLT?

![image](https://user-images.githubusercontent.com/159292/31046037-f84abb4e-a5f1-11e7-9cf5-00f42126128e.png)

**Comment by evilnickname** [comment]
Thanks. I'm working on custom formats for the next release.

**Comment by evilnickname** [comment]
@pmorch I have uploaded a beta version to the [development channel](https://addons.mozilla.org/en-US/firefox/addon/link-text-and-location-copier/#beta-channel), which includes support for custom formats and reordering the context menu (accessible through the preferences page). It uses local storage, so settings are not synced across devices.

Any feedback on this version would be very much appreciated.

**Comment by pmorch** [comment]
It works great. The configuration page does everything it needs to do and is quite usable, but it ain't exactly pretty :-) :

![image](https://user-images.githubusercontent.com/159292/31444499-a805e27c-ae9c-11e7-9bc9-0896a9a1f2f5.png)

However as I said, it is entirely usable.

I can see that the %U and %T tags from CoLT are implemented. One thing I'll miss from CoLT will the link option: Rich Text HTML with Format  {RT}. It copies the link as "[rich text](http://some/url)" for pasting into e.g. LibreOffice as a real hyperlink link. It is not the same as `<a href="%T">%U</a>` that creates the text `<a href="http://some/url">Text</a>`.

But this has come a _long_ way from the static list that was before your work on this. Now link-text-location-copier is a viable replacement for CoLT. Thanks!

It is definitely fine just as it is!

Go forth, be proud and push from development to official channel! :-)

**Comment by evilnickname** [comment]
@pmorch Thanks for testing. I know it's not pretty, I was first trying to get it to work ;-).

Strangely enough, I cannot seem to get changes stored beyond a browser session. Within a session all changes persist, but once I close the browser, it's all gone. Do you have the same problem, or does it work?

Adding Rich Text shouldn't be much of a problem (I saw it in a [web extension demo](https://github.com/mdn/webextensions-examples/tree/master/context-menu-copy-link-with-types), so I know it can be done). The reason it isn't implemented yet is because I have no need for it myself, but I'll create an issue for it.

**Comment by pmorch** [comment]
You're right. The formats are lost when I restart the browser. I didn't think to test for that.

**Comment by evilnickname** [comment]
@pmorch [beta 9](https://addons.mozilla.org/en-US/firefox/addon/link-text-and-location-copier/versions/beta) seems to work even across browser sessions, so if you could test that version, that would be great.

I will test it on my Windows/work PC tomorrow, but I think this this could be the one.

**Comment by evilnickname** [comment]
Version 1.4.0 submitted to AMO.
