### ISSUE TITLE
copy will maybe not work for some users (advanced users?)

### ISSUE THREAD

**Issue by def00111** [evilnickname/link-text-location-copier#7]
Some people have this pref disabled for privacy reasons:
dom.event.clipboardevents.enabled

https://bugzilla.mozilla.org/show_bug.cgi?id=1396275
https://dxr.mozilla.org/mozilla-central/source/dom/base/nsCopySupport.cpp#829

**Comment by evilnickname** [comment]
Thanks for bringing this up. I'm not sure what to do with this, but I can see if I could show some sort of error message when the pref is switched off.

**Comment by evilnickname** [comment]
I've added this to the list of known issues.
