### ISSUE TITLE
Add Rich Text support

### ISSUE THREAD

**Issue by evilnickname** [evilnickname/link-text-location-copier#8]
Requested in #6 by @pmorch:
> One thing I'll miss from CoLT will the link option: Rich Text HTML with Format {RT}. It copies the link as "rich text" for pasting into e.g. LibreOffice as a real hyperlink link.

This is implemented in https://github.com/mdn/webextensions-examples/tree/master/context-menu-copy-link-with-types

**Comment by evilnickname** [comment]
Added Rich Text support in version 1.4.1. You will need to hit 'reset defaults' if you've used version 1.4.0 for it to show up.

**Comment by pmorch** [comment]
Fantastic. Yes, it works exactly like it should. Thanks!
